### ISSUE TITLE
Error when pushing an update

### ISSUE THREAD

**Issue by Irfanwani** [nmengual/code-push-server#2]
After sending an update using the command `code-push-standalone release-react myapp-android android`, it does get uploaded to aws as i can see a file uploaded in my bucket but the server gives this error and the update is never delivered to the apps.

```
Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.
An error was encountered in a non-retryable streaming request.
Unknown error source
NotImplemented: A header you provided implies functionality that is not implemented
at throwDefaultError (/code-push-server/api/node_modules/@smithy/smithy-client/dist-cjs/index.js:836:20)
at /code-push-server/api/node_modules/@smithy/smithy-client/dist-cjs/index.js:845:5
at de_CommandError (/code-push-server/api/node_modules/@aws-sdk/client-s3/dist-cjs/index.js:4739:14)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /code-push-server/api/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
at async /code-push-server/api/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:485:18
at async /code-push-server/api/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
at async /code-push-server/api/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/index.js:263:18
at async /code-push-server/api/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:110:22
at async /code-push-server/api/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14

```

**Comment by nmengual** [comment]
I'll check it out, but I think I know what the problem might be.

**Comment by Irfanwani** [comment]
> I'll check it out, but I think I know what the problem might be.

Please do so. That would be really helpful

**Comment by Irfanwani** [comment]
@nmengual any updates on this?

**Comment by amdrade** [comment]
@nmengual any updates?

**Comment by ryvaldievoid** [comment]
I fix it with adding the content length in the params

[api/script/storage/redis-s3-storage.ts line 535 - 540](https://github.com/nmengual/code-push-server/blob/0e38d25546f4deda39619162dd21423df27ba77b/api/script/storage/redis-s3-storage.ts#L535)

```
public addBlob(blobId: string, stream: stream.Readable, streamLength: number): Promise<string> {
    const params = {
      Bucket: process.env.AWS_BUCKET_NAME,
      Key: blobId,
      Body: stream,
      ContentLength: streamLength
    };
    ...

**Comment by amdrade** [comment]
The upload is successful, but the app does not download the update from S3

**Comment by ryvaldievoid** [comment]
@amdrade you should check your S3 permission, does it allow public download or not.
If you have no access to your S3 storage, you can try to test the blob_url on your terminal with the CLI
 `code-push deployment history APP_NAME DEPLOYMENT_NAME --format json`

See if the blob_url is working as expected or not

**Comment by amdrade** [comment]
On run `code-push deployment history APP_NAME DEPLOYMENT_NAME --format json` return [Error]  socket hang up

**Comment by ryvaldievoid** [comment]
> On run `code-push deployment history APP_NAME DEPLOYMENT_NAME --format json` return [Error] socket hang up

Maybe you should check the official microsoft repo for that error. Quite possibly it's because of the redis or something.
Best of luck to you

**Comment by amdrade** [comment]
@ryvaldievoid Ok, did you get it working with redis and s3?

**Comment by ryvaldievoid** [comment]
@amdrade yes it's working fine on my side

**Comment by amdrade** [comment]
I'm trying to run using docker, registering new apps works, but when I tried to check the download history and remove an app, it didn't work.
